
project_id = "xnrvqfclyroagzknedhs"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://lovable.dev/projects/351714c7-a4c6-4f25-bf5f-a3c37bdee2ed"
additional_redirect_urls = ["https://lovable.dev/projects/351714c7-a4c6-4f25-bf5f-a3c37bdee2ed/**"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"

[functions.create-checkout-session]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.send-subscription-email]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.realtime-prices]
verify_jwt = false

[functions.stream-prices]
verify_jwt = false

[functions.finnhub-websocket]
verify_jwt = false

[functions.get-checkout-session]
verify_jwt = true
